#!/bin/sh
# K-Wrt Default Settings
# Author: Xiaok
# Date: 2024-04-02
# Update: 2024-04-02

build_date=20240402

### For TP-Link
model_name=$(cat /proc/cpuinfo 2>/dev/null | grep TP-LINK 2>/dev/null | awk '{print $4}')
model_version=$(cat /proc/cpuinfo 2>/dev/null | grep TP-LINK 2>/dev/null | awk '{print $5}')

if [ -z $model_name ] ; then
    model_name=K-WRT
fi

host_name=${model_name}
[ ! -z $model_version ] && host_name="${host_name}-$model_version"

sed -i "s/ImmortalWrt/K-Wrt/g" /etc/openwrt_release
sed -i "s/ImmortalWrt/      K-Wrt/g" /etc/banner
sed -i "s/18.06-SNAPSHOT/18.06 @ ${build_date}/g" /etc/openwrt_release
sed -i "s/18.06-SNAPSHOT/18.06 @ ${build_date}/g" /etc/banner

###### Base informations ######
uci set system.@system[0].hostname=$host_name
uci commit system

###### WiFi Settings ######
wifi_0=$(uci get wireless.radio0.hwmode 2>/dev/null)
wifi_1=$(uci get wireless.radio1.hwmode 2>/dev/null)

function set_wifi(){
    _id=$1
    case $2 in
        11g)
            # 2.4G
            uci set wireless.default_radio${_id}.ssid=$model_name
        ;;
        11a)
            # 5G
            uci set wireless.default_radio${_id}.ssid=${model_name}-5G
        ;;
        *)
    esac

    if [ ! -z $2 ] ; then
        uci set wireless.default_radio${_id}.encryption='psk2+tkip+ccmp'
        uci set wireless.default_radio${_id}.key='15084862585'
    fi
}

set_wifi 0 $wifi_0
set_wifi 1 $wifi_1
uci commit wireless

